### ISSUE TITLE
Gem-spec file?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [goncalossilva/acts_as_paranoid#1]
Could you provide a gemspec file for installing it via rubygems?
Thx

**Comment by mdesantis** [comment]
I quote... this plugin is worthy of a gem!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Added gemspec... Look at http://github.com/goncalossilva/rails3_acts_as_paranoid/issues#issue/5

**Comment by goncalossilva** [comment]
Just added a gemspec. You can also install the gem through rubyggems: http://rubygems.org/gems/rails3_acts_as_paranoid

Just "gem install rails3_acts_as_paranoid" :)
