### ISSUE TITLE
Cannot save a deleted record

### ISSUE THREAD

**Issue by CarmelK** [goncalossilva/acts_as_paranoid#103]
I need to create a deleted object. 
Code: record = Mymodel.create(:name => "obj_name", :deleted_at => DateTime.now)
results in: ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved

I use ruby 1.8.7, rails 3.1.11 and "rails3_acts_as_paranoid", "~> 0.1.4"
It did work fine with 'rails', '3.0.20' and "rails3_acts_as_paranoid", "~> 0.0.9"

**Comment by christopherchiu** [comment]
@CarmelK Sorry for the late reply, I just joined this project. As for your issue, I'm surprised you're not getting a can't mass assign protected attribute error. Are you still experiencing this issue?

**Comment by CarmelK** [comment]
Now I use ruby 1.9.3 , acts_as_paranoid 0.4.2, rails 3.2.13 and I don't seem to get any errors, although when trying to save the record , it's being saved without the deleted_at attribute.

**Comment by christopherchiu** [comment]
I'm using the same exact things. Are you still trying to mass assign the field? Because you won't be able to do that. Also, why are you initializing the model with the deleted_at attribute?  Are you trying to create something that is hidden from the get go ?

**Comment by CarmelK** [comment]
I was trying to replicate the error incorrectly in the console, using mass assign.
I am migrating data from one web app to another, some records are deleted, so I am saving them with deleted_at being some date. I stopped copying those records because of the error. I just checked the migration again and it works. 
Thanks @christopherchiu

**Comment by christopherchiu** [comment]
Great! I'm glad it worked out. We just recently pulled in a change that allows you to mass assign deleted_at. If you really need that functionality I suggest you pull directly from branch 3.2 in your gemfile.
