### ISSUE TITLE
Release 0.4.2 with fixes

### ISSUE THREAD

**Issue by avit** [goncalossilva/acts_as_paranoid#112]
It would be appreciated to get a new gem out at least with the fix for the `persisted?` check (#94).

We've been leaning on Github for bundling everything for a while now.

**Comment by chuckg** [comment]
Sorry about that @avit, I don't have access to the RubyGems project to bundle and update it.  @goncalossilva would you mind updating the gem to `0.4.2` on RubyGems and/or adding me to the project?

**Comment by goncalossilva** [comment]
@chuckg which email should I add to the RubyGems project?

**Comment by goncalossilva** [comment]
Released ;-)

**Comment by chuckg** [comment]
@goncalossilva I don't seem to be able to update the gem because I'm only listed as an author, not an "owner". My username is "chuckg" on RubyGems.

**Comment by goncalossilva** [comment]
@chuckg Ah, I see. @technoweenie, could you add ownership to @chuckg on rubygems?

**Comment by technoweenie** [comment]
Sure.  Added @chuckg to [acts as paranoid](http://rubygems.org/gems/acts_as_paranoid).

Nice avatar :)

**Comment by goncalossilva** [comment]
@technoweenie Great, thanks!

**Comment by avit** [comment]
Thank you guys!
