### ISSUE TITLE
Syntactic Sugars 

### ISSUE THREAD

**Issue by alex-zige** [goncalossilva/acts_as_paranoid#113]
Maybe try to extend ActiveSupport::Concern instead of using class_eval so heavily.   Good work though!

**Comment by chuckg** [comment]
Thanks @alex-zige.  While I agree that the use of `class_eval` isn't ideal, I don't think that the _style_ in which the gem is implemented necessarily warrants opening a ticket against it. That is, unless you have are having a particular problem as a result of it; do you?

**Comment by alex-zige** [comment]
I was just looking into the gem source code, haven't found any particular problems yet. but will keep you posted. Just on the note, AS::Concern is more rails-friendly way to deal with extends and open classes nowadays. All good.
