### ISSUE TITLE
Active Record Callbacks not working

### ISSUE THREAD

**Issue by victorhazbunanuff** [goncalossilva/acts_as_paranoid#116]
Rails 3.2.13 has deprecated before_destroy callbacks so this line:
https://github.com/goncalossilva/acts_as_paranoid/blob/rails3.2/lib/acts_as_paranoid/core.rb#L107 will try to run destroy callbacks but it not work because the destroy callbacks are deprecated. instead of:

```
run_callbacks :destroy do
```

do this:

```
run_callbacks :save do
```

Because it is not a destroy action, it is an update.

This is my suggestion https://gist.github.com/victorhazbunanuff/5777082

Thanks!

**Comment by christopherchiu** [comment]
@victorhazbunanuff Has before_destroy really been deprecated? I haven't been able to find any information on that. Can you link me to some documentation? Thank you.

**Comment by victorhazbunanuff** [comment]
@christopherchiu http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html before_destroy method is not there

**Comment by christopherchiu** [comment]
I think that list is mainly to illustrate the order of the callbacks in relation to creation and validation. You can see before_destory getting referenced to throughout the document. Also, I just tested it on a rails app and it seems to be calling it correctly. Have you tested it yourself?

**Comment by victorhazbunanuff** [comment]
Yes, I tested in an app, and it does not run the before destroy callback, I guess that problem is not related to the gem because the before_destroy callback is not deprecated as I think it was. Lets just close this issue, and thanks!

**Comment by christopherchiu** [comment]
All right. I hope you find the source of your issues. Thanks.

**Comment by joshuapinter** [comment]
@victorhazbunanuff Just a though, but it might be that you are calling `#delete` instead of `#destroy` on your object, which doesn't call any callbacks. It caught me off guard as well.
