### ISSUE TITLE
acts_as_tenant gem breaks Recover on my associations

### ISSUE THREAD

**Issue by srb-** [goncalossilva/acts_as_paranoid#119]
Great gem!

I'm running into an issue where I can destroy models and their associations just fine, but when I do a recover on the parent it is not recovering the children as well. The parent is recovered just fine. 

In my sandbox I have narrowed this behavior down to a conflict with the 'acts_as_tenant' gem. 

Basically when I have my Child model roughly:

```
class Child::AR
 belongs_to :Parent
 acts_as_tenant(:account)
 acts_as_paranoid
```

it is NOT recovered when recover the parent. The parent model has:

```
class Parent::AR
 has_many :Child, :dependent => :destroy
 acts_as_tenant(:account)
 acts_as_paranoid
```

When I comment out the acts_as_tenant, it recovers just fine. 

I'm thinking acts_as_tenant is messing with the scoping (but weird that it's only doing it on the children, not the parent.)

Any ideas on how I can get around this issue? 

Many thanks for the great gem!

**Comment by zzak** [comment]
Hello @stephenbeath henbeath,

Thanks for trying the gem, if you could please give our pre-release a try and let me know any issues you run into.

Please re-open the ticket if you're still having difficulties.
