### ISSUE TITLE
on new_record has_many association + with_deleted scope returns all records

### ISSUE THREAD

**Issue by gtournie** [goncalossilva/acts_as_paranoid#122]
Hi,

Let's assume we have theses 2 classes:

Class Thing < ActiveRecord::Base
  acts_as_paranoid
end

Class Example < ActiveRecord::Base
  has_many :things
end

Now calling Example.new.things.with_deleted returns all Thing records in db, instead of none...
SQL: "SELECT `things`.\* FROM `things` WHERE `things`.`example_id` IS NULL"

**Comment by zzak** [comment]
In this case I think both classes need `acts_as_paranoid`, please try it with the latest version (ie: `gem install acts_as_paranoid --pre`) and let me know if that works for you.
