### ISSUE TITLE
acts_as_paranoid and attr_accessible order affects MassAssignementSecurity::Error

### ISSUE THREAD

**Issue by garyharan** [goncalossilva/acts_as_paranoid#125]
In rails 3.2.14 if we have acts_as_paranoid after the attr_accessible call we do not get ActiveModel::MassAssignmentSecurity::Error when we expect them.

**Comment by christopherchiu** [comment]
Interesting. Has your experience been that if you have acts_as_paranoid after attr_accessible then when you do a mass assignment that includes deleted_at it will proceed without giving you a mass assignable security exception for the column deleted_at?

**Comment by garyharan** [comment]
The example I have in mind is that with attr_accessible before acts_as_paranoid I can do the following:

```
Category.new ancestry: "testing"
=> #<Category ancestry: "testing"
```

With attr_accessible after acts_as_paranoid this is what happens (expected behavior):

```
Category.new ancestry: "testing"
=> ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes: ancestry
```

**Comment by christopherchiu** [comment]
Ahh found it. 

``` ruby
attr_protected paranoid_configuration[:column]
```

This sets the column to protected and everything else to accessible. I'll try to get to it soon.

**Comment by christopherchiu** [comment]
@garyharan I just pushed a fix for this. Let me know if it works for you.

**Comment by garyharan** [comment]
Just tested with:

```
gem 'acts_as_paranoid', git: 'https://github.com/goncalossilva/acts_as_paranoid', branch: 'rails3.2'
```

And it worked as expected!

**Comment by christopherchiu** [comment]
Awesome! Thanks for reporting the issue.

**Comment by garyharan** [comment]
@christopherchiu thanks for the fix!  Do you know which version it will be live in?

**Comment by garyharan** [comment]
@christopherchiu will you guys release a version 0.4.3 with this fix any time soon?
