### ISSUE TITLE
paranoiac.destroy! immediate:true

### ISSUE THREAD

**Issue by pannous** [goncalossilva/acts_as_paranoid#129]
suggestion:

 make it possible to destroy records immediately: 
paranoiac.destroy! immediate:true

 instead of paranoiac.destroy!.destroy! which is more costly for the database

**Comment by christopherchiu** [comment]
Calling destroy! should immediately delete the record. The destroy call requires 2 calls, but the destroy! does so immediately. 

Let me know if that's not what you're experiencing.
