### ISSUE TITLE
has_one association and with_deleted

### ISSUE THREAD

**Issue by arius** [goncalossilva/acts_as_paranoid#131]
Hi, pls, 

how can i get deleted record via has_one association?

i try my_association_with_deleted but it's undefined method
i try to insert :with_deleted => true to definition of association but: ArgumentError: Unknown key: with_deleted
i try my_association.with_deleted but it's NoMethodError: undefined method `with_deleted' for nil:NilClass

Some other possibility?
Thanks

**Comment by tak2siva** [comment]
has_one, has_many are not supported!

What you can do is call your 'has_one' or 'has_many' associations like 

Model.association.with_deleted

**Comment by arius** [comment]
But it's not useful if i want to use Ransack for searching/sorting via association in deleted records (i can't create my own scope ignoring acts_as_paranoid default scope, can i? ). Any idea?

**Comment by zzak** [comment]
Unfortunately without a patch I can't accept this feature, please try to write a patch against master, or technoweenie/acts_as_paranoid@master branch.
