### ISSUE TITLE
association does't work as described in readme.

### ISSUE THREAD

**Issue by nfriend21** [goncalossilva/acts_as_paranoid#134]
Plain and simple, this doesnt work:

class Parent < ActiveRecord::Base
    has_many :children, :class_name => "ParanoiacChild"
end

class ParanoiacChild < ActiveRecord::Base
    belongs_to :parent
  belongs_to :parent_including_deleted, :class_name => "Parent", :with_deleted => true
  # You cannot name association *_with_deleted
end

parent = Parent.first
child = parent.children.create
parent.destroy

child.parent #=> nil
child.parent_including_deleted #=> Parent (it works!)

the association returns nil, when Parent.with_deleted returns the record in the result.

**Comment by findchris** [comment]
Was just going to post this.

Also, the classes don't include the `acts_as_paranoid` macro.  Do both classes need that declaration?  Must their paranoid `column_name`s match up?

Thanks.

**Comment by andremedeiros** [comment]
@nfriend21, @findchris:

Both the parent and the child need to include the `acts_as_paranoid` macro, seen as it's what is adding the logic to the scopes, and what allows the `:with_deleted => true` parameter.

**Comment by zzak** [comment]
Please try @andremedeiros's advice, if you are still experiencing issues feel free to re-open the ticket.
