### ISSUE TITLE
Ruby 1.9 problems?

### ISSUE THREAD

**Issue by corroded** [goncalossilva/acts_as_paranoid#19]
Are you using any US-ASCII character in your code or comments? We got an invalid byte sequence in US-ASCII (ArgumentError) while trying to install this in an EngineYard server(confirmed this by commenting out rails3-acts-as-paranoid from Gemfile)

It seems that EngineYard is not(or IS) using UTF8(dunno about locales that much to understand the problem) but it seems you are using an invalid character on your code? It does work on my local, but just wanted to ask what this was all about.

**Comment by goncalossilva** [comment]
No, there is no special characters in the code/comments. Are you using them in your application?

**Comment by corroded** [comment]
heya we found out what was causing the trouble. it was the coding = utf8, and your name apparently: s.authors = ["Gonçalo Silva"] in the gemspec. we forked it and used a normal character for the c if you don't mind. i do suggest you use the normal 'c' so your code can be compatible with some 1.9 versions(im not sure which ruby 1.9 engine yard is using). i do understand if you don't want to change it(since if it was MY name i wouldn't either) :) Thanks for the great code btw

**Comment by goncalossilva** [comment]
Strange... the "# coding: UTF-8" is specifically there to prevent Ruby from failing to parse the "ç". Could you change it to "# encoding: utf-8" and give it a try?

**Comment by jtadeulopes** [comment]
This fork fixed it https://github.com/stalcottsmith/rails3_acts_as_paranoid

**Comment by goncalossilva** [comment]
That fork didn't fix anything, just removed the "culprit" character :)

As I've said, I was unable to reproduce this error. Which ruby version are you using? Did you try my suggestion in the other comment?

**Comment by jtadeulopes** [comment]
ruby 1.9.2p136 (2010-12-25 revision 30365) [i686-linux]
Rails 3.0.6
rubygem 1.3.7

It's only in ubuntu server, not in my macbook and other in my work =/

**Comment by goncalossilva** [comment]
Thanks! I'll try and figure out what's going on.

**Comment by goncalossilva** [comment]
I've just tested it with 1.9.2-p136 and still wasn't able to reproduce this. Is it possible for you to update to p180 and give it try?

**Comment by freddy** [comment]
I've got the same issue on :
ruby 1.9.2p180 (2011-02-18 revision 30909) x86_64-linux
using RVM

Thanks

**Comment by goncalossilva** [comment]
Could you test with master and see if it's fixed?

**Comment by freddy** [comment]
Still bugged, I switched to paranoia, thanks anyway!

**Comment by goncalossilva** [comment]
Changed the magic comment to the variant used in Bundler by default. Does it fix this? I should be able to reproduce this (though I'm not).

**Comment by sagmor** [comment]
Technically is a RubyGems problem. 
The problem occurs when the server's locale is not set to Unicode, check this issue: https://github.com/siefca/i18n-inflector/issues/3
