### ISSUE TITLE
Question: will this work with other plugins with a similar implementation?

### ISSUE THREAD

**Issue by rtomsmith** [goncalossilva/acts_as_paranoid#2]
I guess I'm wondering if this will break if I include another AR plugin with a similar design? You are playing with default_scope and unscoped. For example if my other plugin also has its own default_scope, and I do a with_deleted operation, will the other plugin's default_scope (and/or any standard default_scope declaration) be defeated since with_deleted uses unscoped?

**Comment by goncalossilva** [comment]
Unfortunately, there will be trouble if this is used in conjunction with another plugin/gem which also uses default_scope.

Please avoid this situation.
