### ISSUE TITLE
Inherited models dont inherit acts_as_paranoid properly

### ISSUE THREAD

**Issue by omricohen** [goncalossilva/acts_as_paranoid#21]
Say I have a model:

```
class Attachment < ActiveRecord::Base
  acts_as_paranoid
end
```

and another

```
class Photo < Attachment
end
```

When I try to do a Photo.destroy it fails on the command Photo.paranoid_column. I tried adding acts_as_paranoid to the Photo class as well, but it still errors out. The only way I could get Photo to have acts_as_paranoid working was removing it from the attachment model and only including it in the Photo model. Let me know if you need any more information. Great work other than that ;)

**Comment by goncalossilva** [comment]
Thank you for reporting this bug! Yes, I've just noticed class instance variables weren't being set on inherited paranoid classes.

Please test the latest version (0.0.7) and let me know if you find any problems. Please note that you'll need to call "acts_as_paranoid" from the subclasses as well. I'll try to avoid that in a future release, but for now it's the way to go.

**Comment by goncalossilva** [comment]
It's been 1 month since the last reply. Closing the issue.

**Comment by coneybeare** [comment]
For anybody that stumbles upon this, the correct solution is not to add the "acts_as_paranoid" call to the superclass, but for the subclasses. Then, set abstract_class on the superclass:

``` ruby
class Foo < BaseModel
  acts_as_paranoid
end

class BaseModel < ActiveRecord::Base
  self.abstract_class = true
end
```
