### ISSUE TITLE
Association condition is not getting picked up

### ISSUE THREAD

**Issue by rahul100885** [goncalossilva/acts_as_paranoid#24]
Acts_as_paranoid is not picking association model condition,
e.g

> object = Opportunity.with_deleted.find(2)
> log : Opportunity Load (1.4ms)  SELECT "opportunities".\* FROM "opportunities" WHERE "opportunities"."id" = 2 LIMIT 1
> 
> object.comments.where("title in ('Comment','Note')").order("created_at DESC")
> log : SELECT "comments".\* FROM "comments" WHERE (comments.deleted_at IS NULL) AND ("comments".commentable_id = 2 AND "comments".commentable_type = 'Opportunity') AND (title in ('Comment','Note')) ORDER BY created_at DESC
> 
> object.comments.with_deleted.where("title in ('Comment','Note')").order("created_at DESC")
> log : SELECT "comments".\* FROM "comments" WHERE (title in ('Comment','Note')) ORDER BY created_at DESC

Now as we see when I use with_deleted it is not passing objects condition to comment.

object.comments.where pass condition (comments.deleted_at IS NULL) AND ("comments".commentable_id = 2 AND "comments".commentable_type = 'Opportunity') like object.comments.with_deleted.where should pass

**Comment by jmoses** [comment]
It's because the with_deleted does unscoped, which yanks _any_ scopes, including relation scopes.  I'll probably make a pull request for this.  It's annoying.

**Comment by tomoyuki28jp** [comment]
I think I am facing the same issue. `current_user.messages.with_deleted` returns messages whose owner isn't the current user. It's annoying.

**Comment by goncalossilva** [comment]
This is the same issue, right? https://rails.lighthouseapp.com/projects/8994/tickets/5909-unscoped-on-a-relation-removes-where-clause-for-relation-from-scope

If you want a quick fix, you can use:

```
Comment.with_deleted do
   object.comments
end
```

**Comment by goncalossilva** [comment]
I'm inclined to say that this is a Rails issue (link above), so I'm closing this for now... if you need a solution, check my code snippet on the above comment.

**Comment by jugyo** [comment]
I think your code will not work.
It seems that the with_deleted does not handle the block.
