### ISSUE TITLE
Still getting destroyed for nested-attributes?

### ISSUE THREAD

**Issue by silasb** [goncalossilva/acts_as_paranoid#29]
I have a parent model call Member which has many memberhips.  I am not using dependent => :destroy but when I using nested-attributes by assigning:

```
'memberships_attributes' => {'0' => {'_destroy' => '1'}}
```

It will still do a hard destroy.  Is there something that I am doing wrong?

I'm running 1.9.2-p180 with RoR 3.0.9

**Comment by goncalossilva** [comment]
Could you post a more elaborate example? Please test the latest version from master and check if this is still happening.

**Comment by goncalossilva** [comment]
I'm closing this issue. Please test the latest version and see if this error is still there (I believe it isn't). If it is, reopen this issue. Thanks.
