### ISSUE TITLE
recover and after_destroy callbacks do not seem to work

### ISSUE THREAD

**Issue by sumangurung** [goncalossilva/acts_as_paranoid#3]
I was using this plugin with my rails3 app on ruby 1.9.2 and found that recovering a deleted record and after_destroy callback are not working.

**Comment by goncalossilva** [comment]
Could you please provide more details?

Rails 3 stable or one of the beta/rc? Which version? What about your model: how was acts_as_paranoid called?

**Comment by sumangurung** [comment]
With the rc and the stable. 
In the model, i have 
class SomeClass < ActiveResource::Base
  acts_as_paranoid
  after_destroy :some_method
  def some_method
    puts "test"
  end
end

In your destroy method, you should do something like this

def destroy
  _run_destroy_callbacks do
     whatever_you_have_in_your_current_destroy_method_goes_here
  end
end

Hope this helps.

**Comment by sumangurung** [comment]
Oh and the you cannot do the update_attributes on the recover method because of the default scope.

**Comment by goncalossilva** [comment]
I've just merge Juan Pemberthy's changes which address this issue. It should be fixed.

Sorry for taking so long—I wasn't able to find some time to address this myself.

Thank you for reporting this issue.
