### ISSUE TITLE
custom uniqueness validators broken with rails 3.1

### ISSUE THREAD

**Issue by lypanov** [goncalossilva/acts_as_paranoid#40]
NoMethodError (undefined method `mount_sql_and_params' for #ParanoidValidations:UniquenessWithoutDeletedValidator:0x11e79418):

**Comment by goncalossilva** [comment]
Maybe @gravelpup could take a look at this? He is the author of the paranoid validators.

**Comment by tute** [comment]
Method removed from Rails 3.1. Added to an initialiazer and it works: http://apidock.com/rails/ActiveRecord/Validations/UniquenessValidator/mount_sql_and_params

**Comment by goncalossilva** [comment]
Thanks for reporting. Fixed on "master", "rails3.1" and "rails3.2".
