### ISSUE TITLE
For paranoid_column which is not attr_accessible

### ISSUE THREAD

**Issue by yu-yu** [goncalossilva/acts_as_paranoid#45]
I don't want my :deleted_at column to be in attr_accessible columns.
How about this? :)

https://github.com/yu-yu/rails3_acts_as_paranoid/commit/20dad3639b2403780543ff9a692d459e2b773963

**Comment by goncalossilva** [comment]
Seems good. Could you send a pull request?

**Comment by yu-yu** [comment]
I'm glad. 

I'm afraid I don't have any email address I can use for a git commit in public.
so,,, could you create a commit to do this change?

**Comment by goncalossilva** [comment]
Thanks.

**Comment by yu-yu** [comment]
Thank you, too.
