### ISSUE TITLE
with_deleted does not cooperate with scopes

### ISSUE THREAD

**Issue by leonid-shevtsov** [goncalossilva/acts_as_paranoid#50]
Let's say we have a model

```
class Article
  acts_as_paranoid
  scope :latest, order('created_at DESC')
end
```

Then

```
Article.with_deleted.latest
```

produces only undeleted articles, and

```
Article.latest.with_deleted
```

produces all articles, including deleted ones, but without any ordering.

This is expectable since `with_deleted` is basically an alias to `unscoped`, but it's not the right nor the obvious way how this scope should work.

**Comment by goncalossilva** [comment]
It does now! Please check the "rails3.2" branch.
