### ISSUE TITLE
ActsAsParanoid::Associations should be added to ActiveRecord::Base

### ISSUE THREAD

**Issue by pcreux** [goncalossilva/acts_as_paranoid#58]
`ActsAsParanoid::Associations` is only added to class acting as paranoid.

To get a non paranoid class to `belong_to :with_deleted => true` you have to include `ActsAsParanoid::Associations`.

``` ruby
class MyClassWithoutActsAsParanoid < ActiveRecord::Base

  include ActsAsParanoid::Associations
  belongs_to :paranoiac_model, :with_deleted => true

end
```

What about including `ActsAsParanoid::Associations` to `ActiveRecord::Base` by default?

**Comment by chuckg** [comment]
+1 -  there are situations where the model creating an association to a paranoid model is not itself paranoid.

**Comment by goncalossilva** [comment]
Please test with master.

**Comment by goncalossilva** [comment]
Not sure why this is still opened, since the current version already does this. Lousy maintainer :p
