### ISSUE TITLE
Object fetched with 'select' options can't be used unless the deleted_at field is specified

### ISSUE THREAD

**Issue by maxime-menant** [goncalossilva/acts_as_paranoid#60]
I have an issue when I fetch only an attribute subset from my paranoid model using 

``` ruby
Object.select([:id, :relation_id, :type]).first
```

on a PostgreSQL DB, which return only an instance with these attributes, and when I try to generate a route for this instance, acts_as_paraonoid break since the column :deteled_at is not present

``` ruby
# acts_as_paranoid/core.rb - line 70    
def paranoid_value
  self.send(self.class.paranoid_column)
end
```

Should I had the deleted_at attribute in my select each time ? Or should the core of acts_as_paranoid check if the instance respond to :deteled_at ?

**Comment by zzak** [comment]
You need to include `:deleted_at` in the select query.

Please re-open the issue if you continue to experience difficulty.
