### ISSUE TITLE
with_deleted options by associations still a bit buggy

### ISSUE THREAD

**Issue by HoneyryderChuck** [goncalossilva/acts_as_paranoid#61]
Hi,

I'm having some issues with the with_deleted option. First, I can't seem to use it in classes that are not paranoid. Well, I think I should do that, because in such cases the association should be paranoid. Something like this:

<pre>
<code>
class NotParanoid < ActiveRecord::Base

# not calling acts_as_paranoid here
:belongs_to :paranoid_object, :with_deleted => true

end
</code>
</pre>

I found a workaround, which was to include the following line:

<pre>
<code>
include ActsAsParanoid::Associations
</code>
</pre>

right before the association definition. Still, I think that the belongs_to_with_deleted options should be included in AR, and not only made acessible when one calls acts_as_paranoid. This was at least the behaviour in rails 2, which was quite alright semantically. 

Another issue is that it doesn't work very well for the polymorphic case. Consider this definition:

<pre>
<code>
class NotParanoid &lt; ActiveRecord::Base

include ActsAsParanoid::Associations
:belongs_to :paranoid_object, :polymorphic => true, :with_deleted => true
end

paranoid_android = NotParanoid.new
paranoid_android.paranoid_object
#=> NoMethodError: undefined method `paranoid?' for nil:NilClass
    from /Users/tiagocardoso/Projects/restorm-com/vendor/bundler_gems/ruby/1.8/gems/rails3_acts_as_paranoid-0.2.2/lib/acts_as_paranoid/associations.rb:19:in `changeable'
</code>
</pre>

as you can see in the source code, this error comes from line 20 of the associations.rb file:

<pre>
<code>
return #{target}_without_unscoped(*args) unless association(:#{target}).klass.paranoid?
</code>
</pre>

so, what's missing here (and correct me if I'm wrong) is to check the options parameter of the association (to see if it is polymorphic) and see if by any chance the class is defined by a field from the object. So, I would replace this line with:

<pre>
<code>
asso = association(:#{target})
klass = if asso.options[:polymorphic] 
klass = asso.owner.send(:#{target}_type)
klass.constantize unless klass.nil?
else
asso.klass
end
return nil if klass.nil?
return #{target}_without_unscoped(*args) unless klass.paranoid?
</code>
</pre>

it can get syntactically prettier, but it works. So, tell me what you think of this. 

Abraço,
Tiago

**Comment by chuckg** [comment]
I agree with you on the first point, the `:with_deleted` option should be available for use with `belongs_to` on any class, regardless of it's status as a paranoid object.  This issue is also discussed here:
https://github.com/goncalossilva/rails3_acts_as_paranoid/issues/58

Your example is likely failing with `NoMethodError: undefined method 'paranoid?' for nil:NilClass` because the class, `ParanoidObject`, does not exist. By using `association(:target)` the code side-steps all the problems with polymorphism and allows AR to determine (and rightly so, the shit internally is crazy!) what `association(:paranoid_object).klass` resolves to. I believe the polymorphic case is tested using a custom `:class_name` option, check out `test/test_associations.rb`.

**Comment by HoneyryderChuck** [comment]
<pre>
<code>
<i>
Your example is likely failing with NoMethodError: undefined method 'paranoid?' for nil:NilClass because the class, ParanoidObject, does not exist.
</i>
</code>
</pre>


Well, not exactly the ParanoidObject class, but the association class that comes from the object attribute (which was not set yet). I think what is missing in the tests is the test for when a polymorphic association does not exist (must return nil).

**Comment by goncalossilva** [comment]
Regarding the first issue, please test with the master branch. The latest commits should fix it.

@chuckg Mind taking a look at the code?

**Comment by chuckg** [comment]
Looks good.

**Comment by HoneyryderChuck** [comment]
is the version currently in master targeted with a version number, or do I have to explicitly download the gem and bundle it locally? For the latter, when will it be attributed a version number?

**Comment by goncalossilva** [comment]
To try master out, all you need to do is to specify it in the Gemfile of your app: `gem 'rails3_acts_as_paranoid', :git => 'git://github.com/goncalossilva/rails3_acts_as_paranoid.git'`

**Comment by ghost** [comment]
Do you know when this will be added to an actual release of the gem other than the master branch?
