### ISSUE TITLE
The override of `destroyed?` breaks url generation

### ISSUE THREAD

**Issue by halorgium** [goncalossilva/acts_as_paranoid#68]
This is a tricky situation. 
I want to allow users to access their destroyed resources via the web. 

The polymorphic route generation in Rails checks to see if the model is `persisted?`. 
But `persisted?` checks if it is not `destroyed?`. 

https://github.com/rails/rails/blob/v3.2.3/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb#L107

Maybe it would be best to change `persisted?` to be `true` and continue to have `destroyed?` be dependent on `paranoid_column`.

**Comment by chuckbergeron** [comment]
+1

I believe this is the same issue I'm running into. I can do route generation on a specific resource if it's active, but as soon as I try to render one that's 'deleted?' it crashes with a routing error.

Basically, I want to show a list of archived (or deleted) records to the CMS user.

**Comment by halorgium** [comment]
I added this to an initializer: 

``` ruby
ActiveRecord::Base.class_eval do
  # revert AR paranoid to original behavior
  def persisted?
    !(new_record? || @destroyed)
  end
end
```

**Comment by chuckbergeron** [comment]
Right on, I'll give it a shot!

...

Yep, that did it. Strange, when I dove into the source I couldn't see at a glance where 'persisted?' had been overriden.

**Comment by joshminnie** [comment]
+1

I was experiencing the same problem and the suggestion by halorgium fixed this for me as well.  I wonder if this is going to be corrected so that acts_as_paranoid can handle this situation more gracefully.

**Comment by chuckbergeron** [comment]
Well, one of us could take the reins and contribute the patch back into master with a pull request. Perhaps I'll do that tomorrow...

**Comment by chuckbergeron** [comment]
tomorrow == a month. You know how it is. 

I finally got around to patching this. Thanks to @halorgium for the patch!

https://github.com/goncalossilva/rails3_acts_as_paranoid/pull/82

**Comment by halorgium** [comment]
Haha, awesome. :+1:
