### ISSUE TITLE
arel sub calls to "joins" don't insert the condition in the "on" block

### ISSUE THREAD

**Issue by HoneyryderChuck** [goncalossilva/acts_as_paranoid#71]
Hi Hi,

I just found a nuisance concerning writing scopes. Lets say I have a Class1, and a Class2 that is paranoid. If somehow I end up writing a scope (or for that matter, just using plain ARel) in the Class1 that joins with Class2, and if instead of writing the SQL myself, I use the symbolic way of writing it, the deleted_at condition doesn't get added. Something like this:

<pre>
<code>
class Class1 &lt; ActiveRecord::Base

has_many :class2s

scope with_class2s, joins(:class2s).where(:field1 => true)

end
</code>
</pre>

just by using the to_sql function, you can see that the condition " AND 'class2'.'deleted_at' IS NULL " isn't part of the ON condition block from the INNER JOIN. Is there a way to fix that? 

Cheers, 
Tiago

**Comment by pelargir** [comment]
+1

I'm having this problem too.

**Comment by davidguthu** [comment]
Same.

**Comment by gugl** [comment]
+1
having the same problem

**Comment by zlx** [comment]
+1 need fixed

**Comment by zlx** [comment]
I make a attempt by override [JoinAssociation#build_constraint](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/join_dependency/join_association.rb#LC145).
It Add `deleted_at is null` to join condition, and may solve the problem

**Comment by markedmondson** [comment]
This solution works in theory but kills the ability to then query .with_deleted and lose the join constraint.

The ideal fix would be to throw a with_deleted option onto the has_many association and use that to optionally add the constraint.

**Comment by zzak** [comment]
We are no longer maintaining this fork, please resubmit this to the upstream: https://github.com/technoweenie/acts_as_paranoid
