### ISSUE TITLE
uniqueness validations not paranoid-implicit

### ISSUE THREAD

**Issue by HoneyryderChuck** [goncalossilva/acts_as_paranoid#80]
Greetings

I just realized that, even though a model is marked as paranoid, the uniqueness validations are not taking that into account explicitly:

``` ruby
class Bong < ActiveRecord::Base
  has_many :tests
end

class Test < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :bong
  validates :bong_id, :uniqueness => { :scope => [:bong_id, :deleted_at] }
  validates :bong_id, :uniqueness => { :scope => :bong_id }

end


```

first validation works. Second doesn't. I haven't tried with uniqueness => true, but chances are, it is also incorrect. Basically, I would like not to be explicit about deleted_at, since the model is already marked as paranoid, it should take this information into account.

**Comment by chuckg** [comment]
Sorry Tiago, could you please clarify your use case? I'm not sure the code you pasted came through correctly. Specifically, could you write out the model, the validations, and the queries that are returning the wrong results (and what was expected)? Thanks!

**Comment by HoneyryderChuck** [comment]
ouch!! it really is totally wrong. I'm editing it right away.

**Comment by zzak** [comment]
I'm honestly a little paranoid about this issue, and think we should close it.

Please re-open if you're still experiencing difficulty.
