### ISSUE TITLE
Association with_deleted for HABTM

### ISSUE THREAD

**Issue by kelso** [goncalossilva/acts_as_paranoid#83]
I have a relation in model Advertiser

```
has_and_belongs_to_many :agencies
```

In advertiser's edit form, I have multiselect for :agency_ids and I would like to see deleted agencies here too (if they were assigned and then deleted)

```
= f.select :agency_ids, Agency.all.collect{|f| [f.name, f.id]}, {}, {:multiple => true, :size => 5}
```

I need something like

```
has_and_belongs_to_many :agencies, :with_deleted => true
```

This work already for `has_many` and `belongs_to`, but it is missing for `has_and_belongs_to_many`.

**Comment by alexparker** [comment]
You mention has_many works for you, it is not working for me. Can you help out?
#91

**Comment by kelso** [comment]
When I wrote it is working on has_many, I probably made a mistake.

You can use built-in scope "with_deleted".

```
user.posts              # returns only non deleted
user.posts.with_deleted # returns posts including deleted
```

And solution for my habtm select seems to be like this:

```
= f.select :agency_ids, Agency.with_deleted.collect{|f| [f.name, f.id]}, {}, {:multiple => true, :size => 5}
```

**Comment by alexparker** [comment]
Ah ok. I have an association that is 

``` ruby
(in user.rb)
has_many :payments, :through => :items
```

and i am calling

``` ruby
user.payments.select(...).where(...).group(...)
```

but I would like to do 

``` ruby
user.payments.with_deleted.select(...).where(...).group(...)
```

How can we get this working??

**Comment by zzak** [comment]
Please include `:deleted_at` in your select query.

Thanks, and please re-open if you continue to experience difficulty.
