### ISSUE TITLE
Chicken && Egg

### ISSUE THREAD

**Issue by dexion** [goncalossilva/acts_as_paranoid#88]
After the latest update of this gem, I can't migrate my db. Error is:

```
undefined local variable or method 
`acts_as_paranoid' for User(Table doesn't exist):Class
```

Before update all works greate!

problem with devise route:

```
devise_for :users, :path_prefix => 'd', :controllers => { :registrations => :registrations, :omniauth_callbacks => "users/omniauth_callbacks" }
```

```
ActionController::RoutingError (undefined local variable or method `acts_as_paranoid' for #<Class:0xc4a01d0>):
```

```
# encoding: utf-8
class User < ActiveRecord::Base
  acts_as_paranoid
end
```

**Comment by christopherchiu** [comment]
@dexion Hi, are you still getting this issue? I wasn't able to reproduce it.

**Comment by tranvictor** [comment]
I cant reproduce this issue too, @dexion is this issue still happening for you? You should close this issue if it's not.

**Comment by dexion** [comment]
Sorry, I don't use acts_as_paranoid. I use paranoia instead. After so many time I close this ticket because it irrelevant
