### ISSUE TITLE
Unable to update a deleted record

### ISSUE THREAD

**Issue by byroot** [goncalossilva/acts_as_paranoid#89]
Hi,

When I try to update a deleted record the guard sql clause get appended:

``` ruby
>> initiative.update_column(:organization_id, organization.id)
  SQL (24.6ms)  UPDATE `product` SET `organization_id` = 30685 WHERE `product`.`id` = 8 AND (`product`.`deleted` = 0)
=> false
```

the only workaround I found is:

``` ruby
>> Initiative.with_deleted.where(id: initiative.id).update_all(organization_id: organization.id)
  SQL (35.3ms)  UPDATE `product` SET organization_id = 30685 WHERE `product`.`id` = 8
```

Am I missing something ?

Regards.

**Comment by chuckg** [comment]
Hi byroot.  Can I ask why you're opting to use `update_column` instead of `update_attribute` or `update_attributes`?  The following works:

``` ruby
initiative = Initiative.only_deleted.first
initiative.deleted? => true
initiative.update_attribute(:organization_id, 1)
```

Using `update_attribute` has the side-effect of saving the model, whether it's dirty or not.  If you're trying to use `update_column` for that reason, the solution you have proposed is the same way I would go about it. The offending code in `update_column` is on line 197 of `ActiveRecord::Persistence`, where it makes a generic call to the class (which is scoped by ActsAsParanoid):

``` ruby
updated_count = self.class.update_all({ name => value }, self.class.primary_key => id)
```

A possible solution added to `acts_as_paranoid` fixed the issue for me:

``` ruby
def update_column(name, value)
  self.class.with_scope(self.class.with_deleted) do
    super
  end
end
```

Needs tests, but I think that'd do it.

**Comment by byroot** [comment]
hi @chuckg,

I'm using update_column because it's in a migration script in a rails app built upon a legacy database from a non-rails application. So this way i avoid all possible validation errors.

I didn't had the time to check for the issue when I saw it, but your answer seem logical. You should create a pull request with it.

If you are to lazy to write the tests let me know I'll do it.

Thanks again.

**Comment by byroot** [comment]
Oops I just figured out that you are one of the maintainers :)

**Comment by chuckg** [comment]
I think fixing `update_column` is the way to go though, there's no reason for it not to work properly.  Though, you do skip validations with `update_attribute` as well.  From the documentation of `update_attribute`:

```
 * Validation is skipped.
 * Callbacks are invoked.
 * updated_at/updated_on column is updated if that column is available.
 * Updates all the attributes that are dirty in this object.
```

And `update_column`:

```
 * Validation is skipped.
 * Callbacks are skipped.
 * updated_at/updated_on column is not updated if that column is available.
```

**Comment by byroot** [comment]
Oh ! you're right. Thanks.

**Comment by christopherchiu** [comment]
@chuckg Do we want to keep this open?

**Comment by chuckg** [comment]
Nope. We can either create a separate feature issue that's more specific about what needs to be added/done or wait and see if someone is interested enough to create a pull request with a fix. Thank you for helping!

**Comment by markedmondson** [comment]
I just got hit by this. Again, while migrating also so was using update_column to skip callbacks.

The issue is that calling update_column always suffixes the paranoid attribute and you can't update a column on a deleted record.

**Comment by avegancafe** [comment]
Would very much like to reopen this issue, did anyone find a fix?
