### ISSUE TITLE
#with_deleted very slow

### ISSUE THREAD

**Issue by cheerfulstoic** [goncalossilva/acts_as_paranoid#9]
I'm running Rails 3.0.1 and on some of my large table I noticed some slowness when using #with_deleted.  I do the following to show the queries that are being executed:

```
ActiveRecord::Base.logger = Logger.new(STDOUT)
```

And when I use #with_deleted I see it selecting \* from every row in the table before moving onto the real query.  I think this has to do with the following change:

https://github.com/goncalossilva/rails3_acts_as_paranoid/commit/e7dd9f56a73d2644691980a1e05c616e789c5464

Is it possible to change the "reload" back to "where" but put an empty string as an argument (as in: ".where('')")?  I'm not sure which tests were failing.  This works for me and doesn't cause the query of the whole table.  Is there a better solution, perhaps?

**Comment by goncalossilva** [comment]
Just reverted that change. All tests are passing. Thanks for noticing the performance regression.
