### ISSUE TITLE
datetime instead of time as column type

### ISSUE THREAD

**Issue by myKingEdem** [goncalossilva/acts_as_paranoid#90]
Shouldn't the default column type be datetime instead of time. That way you could retrieve all deleted records based on day, month, and year. instead of time. Who retrieves archived records  2 minutes  from now.  You retrieve archived records days, months, and even years from now!

**Comment by stevschmid** [comment]
Agreed. I don't understand why time is the default type.

**Comment by chuckg** [comment]
I agree! Pull request away. :shit:

**Comment by silasb** [comment]
Look at https://github.com/radar/paranoia instead.  It uses `datetime` by default.

**Comment by zzak** [comment]
Please feel free to submit a patch against technoweenie/acts_as_paranoid@master branch.

Thanks!
