### ISSUE TITLE
can't use :with_deleted on has_many

### ISSUE THREAD

**Issue by billingb** [goncalossilva/acts_as_paranoid#91]
When trying to use :with_deleted on a has_many I get an error.

Code:
has_many :phone_numbers, :autosave => true, :validate => true, :dependent => :destroy, :with_deleted => true

Error:
/sharehome/billinb/gem/gems/activesupport-3.2.8/lib/active_support/core_ext/hash/keys.rb:51:in `block in assert_valid_keys': Unknown key: with_deleted (ArgumentError)
    from /sharehome/billinb/gem/gems/activesupport-3.2.8/lib/active_support/core_ext/hash/keys.rb:50:in`each_key'
    from /sharehome/billinb/gem/gems/activesupport-3.2.8/lib/active_support/core_ext/hash/keys.rb:50:in `assert_valid_keys'
    from /sharehome/billinb/gem/gems/activerecord-3.2.8/lib/active_record/associations/builder/association.rb:33:in`validate_options'
    from /sharehome/billinb/gem/gems/activerecord-3.2.8/lib/active_record/associations/builder/association.rb:24:in `build'
    from /sharehome/billinb/gem/gems/activerecord-3.2.8/lib/active_record/associations/builder/collection_association.rb:23:in`build'
    from /sharehome/billinb/gem/gems/activerecord-3.2.8/lib/active_record/autosave_association.rb:139:in `build'
    from /sharehome/billinb/gem/gems/activerecord-3.2.8/lib/active_record/associations/builder/has_many.rb:10:in`build'
    from /sharehome/billinb/gem/gems/activerecord-3.2.8/lib/active_record/associations/builder/collection_association.rb:13:in `build'
    from /sharehome/billinb/gem/gems/activerecord-3.2.8/lib/active_record/associations.rb:1195:in`has_many'
    from /sharehome/billinb/workspace/edb/app/models/contact.rb:23:in `<class:Contact>'
    from /sharehome/billinb/workspace/edb/app/models/contact.rb:1:in`<top (required)>'
    from /sharehome/billinb/gem/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
    from /sharehome/billinb/gem/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`block in require'
    from /sharehome/billinb/gem/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /sharehome/billinb/gem/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`require'
    from /sharehome/billinb/gem/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:359:in `require_or_load'
    from /sharehome/billinb/gem/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:313:in`depend_on'
    from /sharehome/billinb/gem/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:225:in `require_dependency'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/engine.rb:439:in`block (2 levels) in eager_load!'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/engine.rb:438:in `each'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/engine.rb:438:in`block in eager_load!'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/engine.rb:436:in `each'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/engine.rb:436:in`eager_load!'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/initializable.rb:30:in`instance_exec'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `run'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `each'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/initializable.rb:54:in`run_initializers'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/application.rb:136:in `initialize!'
    from /sharehome/billinb/gem/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /sharehome/billinb/workspace/edb/config/environment.rb:5:in `<top (required)>'
    from /sharehome/billinb/workspace/edb/test/test_helper.rb:2:in`require'
    from /sharehome/billinb/workspace/edb/test/test_helper.rb:2:in `<top (required)>'
    from /sharehome/billinb/workspace/edb/test/unit/contact_test.rb:1:in`require'
    from /sharehome/billinb/workspace/edb/test/unit/contact_test.rb:1:in `<top (required)>'
    from /sharehome/billinb/gem/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:15:in`require'
    from /sharehome/billinb/gem/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
    from /sharehome/billinb/gem/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4:in`select'
    from /sharehome/billinb/gem/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4:in `<main>'

**Comment by alexparker** [comment]
+1
Yes, this is odd this doesn't work. In your readme.md file it definitely leads one to believe this would just work. Not sure if its a bug, or if it was not implemented.

**Comment by kelso** [comment]
You can use built-in scope "with_deleted".

```
user.posts              # returns only non deleted
user.posts.with_deleted # returns posts including deleted
```

**Comment by rmello** [comment]
+1
It would be nice to allow "permanent" with_deleted associations.
In my case a User has_many Subscriptions (with_deleted) but has_one Subscription (only one subscription of each user may be active at any time) - So I would be able to do:
user.subscription (to return only the active one)
user.subscriptions (to return the active and the deleted ones)

**Comment by zzak** [comment]
currently there is no support for default scope with_deleted, but we're looking into adding it.

there's a duplicate ticket and patch submitted to support this, so i'm closing this one.
